# Site settings
title: Anna Medvedeva
name: Anna Medvedeva

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: GitHub
   url: https://github.com/Medanya
 - title: LinkedIn
   url: https://www.linkedin.com/in/anna-medvedeva-abbbb6146/

#Any buzzword skills you want to include
skills:
 - Computer Vision
 - Python
 - Machine Learning
 - ML/DL stack: numpy, scikit-learn, pandas, Tensorflow
 - C++
 - SQL
 - Map-Reduce
 - Mathematics

#Work experience is required
roles:
 - title: Software Developer
   start: Feb 2018
   end: Present
   employer: Yandex Technologies
   description: "Development of computer vision technologies: factors for search engine and common using, image quality enhancement"
 - title: Junior Data Analyst
   start: Aug 2017
   end: Feb 2018
   employer: Yandex data Factory
   description: Development of moderation systems, machine learning for gold mining industry.
 - title: Analyst Intern
   start: March 2017
   end: August 2017
   employer: Yandex Data Factory
   description: Doing image classification for moderation systems, machine learning for oil industry.
 - title: Developer Intern
   start: October 2017
   end: January 2018
   employer: IBM
   description: Development of projects using data analysis technologies.
 - title: Summer Intern
   start: June 2017
   end: August 2017
   employer: QB Financt
   description: Working on a financial trading algorithms using machine learning.

#Education is required
education:
 - level: Bachelor of Science (B.Sc.)
   date: 2019
   subject: Applied Mathematics and Informatics
   school: Moscow Institute Of Physics and Technologies
 - level: Master of Science (B.Sc.)
   date: 2019
   subject: Applied Mathematics and Informatics
   school: Moscow Institute Of Physics and Technologies  
 - level: Master of Science (B.Sc.)
   date: 2019
   subject: Big Data
   school: Yandex Data Analisys School

intro: |
#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
   