# Site settings
title: Anna Medvedeva
name: Anna Medvedeva

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: GitHub
   url: https://github.com/Medanya
 - title: LinkedIn
   url: https://www.linkedin.com/in/anna-medvedeva-abbbb6146/

#Any buzzword skills you want to include
skills:
 - Computer Vision
 - Python
 - Machine Learning
 - Tensorflow
 - C++
 - SQL
 - Map-Reduce
 - Sklearn, opencv, pandas
 - Mathematics

#Work experience is required
roles:
 - title: Software Developer
   start: Feb. 2018
   end: Present
   employer: Yandex Technologies
   description: "Development of computer vision technologies: factors for search engine and common using, image quality enhancement"
 - title: Junior Data Analyst
   start: Aug. 2017
   end: Feb. 2018
   employer: Yandex data Factory
   description: Development of moderation systems, domain adaptation for celebrities search, machine learning for gold mining industry.
 - title: Analyst Intern
   start: Mar. 2017
   end: Aug. 2017
   employer: Yandex Data Factory
   description: Doing image classification for moderation systems, data analisys for oil industry.
 - title: Developer Intern
   start: Oct. 2017
   end: Jan. 2018
   employer: IBM
   description: Development of projects using IBM data analysis technologies.
 - title: Summer Intern
   start: Jun. 2017
   end: Aug. 2017
   employer: QB Finance
   description: Working on a financial trading algorithms using machine learning and deep learning.

#Education is required
education:
 - level: Master of Science (B.Sc.)
   date: Jul. 2019
   subject: Applied Mathematics and Informatics
   school: Moscow Institute Of Physics and Technologies  
 - level: Master of Science (B.Sc.)
   date: Jun. 2019
   subject: Big Data
   school: Yandex Data Analisys School
 - level: Bachelor of Science (B.Sc.)
   date: May 2017
   subject: Applied Mathematics and Informatics
   school: Moscow Institute Of Physics and Technologies

intro: |
  I am a developer with 2.5 years experience in computer vision. I have experience in deep learning for applied tasks using tensorlfow and deploy using python and C++. I like to read articles in the field of artificial intelligence and try interesting ideas in practice. Our sphere is developing so rapidly! I get pleasure when machine learning really helps people and saves resources.
#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
  I have a publication in the field of random graphs (<a href="http://www.mathnet.ru/php/archive.phtml?wshow=paper&jrnid=mzm&paperid=10853&option_lang=eng">link</a>) <br> <br>

  My bachelor thesis is on the topic of machine learning for fMRI data. We have found that audio data can be used to statistically significantly predict the activation of brain zones (<a href="https://yadi.sk/d/V1cJOJmr3JLibW">link </a>). <br> <br>

  I have been playing chess for a long time and have the title of candidate to the master. Now I like to read chess news and watch broadcasts. <br> <br>

